### PR TITLE
feat: previous and next buttons at bottom of lesson

### PR DESCRIPTION
**Pull request by saumyasinghal747**

### CODE REVIEW

**Comment by saumyasinghal747** [comment]
This is quite bad, since the layout on mobile screens is most ugly.

**Review by syz16 — COMMENTED** [review]
I assume you're going to fix the mobile thing

**Comment by saumyasinghal747** [comment]
I think that last commit should have fixed the mobile view quite well, could you take a look? @sophiazhu16

**Comment by saumyasinghal747** [comment]
This is  actually quite bad still, as the side navbar overflows 
image

**Comment by saumyasinghal747** [comment]
Alright cool, I think we're good to go. Whenever you're ready, Sophia!

**Pull request merged**
